name: astrotak
description: An application to talk with astrologer.

publish_to: 'none'

# current app version
version: 1.0.0+1

# sdk eviornment sdk constrains
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  # for netowrk requests
  dio: ^4.0.4

  # for overriding quality operator
  equatable: ^2.0.3

  # flutter sdk
  flutter:
    sdk: flutter

  # state management libraby 
  flutter_bloc: ^8.0.1

  # dependemcy injection tool
  get_it: ^7.2.0

  # for immutability
  freezed: ^1.1.1

  # for freezed annotations
  freezed_annotation: ^1.1.0
  

dev_dependencies:

  # for linting purpose
  flutter_lints: ^1.0.0

  # code generation
  build_runner: ^2.1.7

  # testing libraby
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    # this will reference all assets in root assets folder
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
